# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumanage', '0002_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='任务步骤')),
                ('desc', models.CharField(default=None, max_length=1000, null=True, verbose_name='步骤描述')),
                ('answer', models.CharField(default=None, max_length=1000, null=True, verbose_name='该步骤的参考答案')),
                ('score_standard', models.CharField(default=None, max_length=1000, null=True, verbose_name='评分标准')),
                ('attachment', models.CharField(default=None, max_length=100, null=True, verbose_name='附件脚本')),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=10, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='学生年龄'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='学生邮箱'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='手机'),
        ),
    ]
