# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stumanage', '0004_auto_20190811_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieView',
            new_name='Movie',
        ),
    ]
