import turtle
turtle.screensize(2000,800)
turtle.showturtle()
turtle.right(60)
turtle.begin_fill()
turtle.circle(100,steps = 3)
turtle.color("black")
turtle.end_fill()
turtle.left(60)
turtle.penup()
turtle.goto(200,0)
turtle.pendown()
turtle.right(45)
turtle.begin_fill()
turtle.circle(100,steps = 4)
turtle.color("black")
turtle.end_fill()
turtle.left(45)
turtle.penup()
turtle.goto(400,0)
turtle.pendown()
turtle.right(36)
turtle.begin_fill()
turtle.circle(100,steps = 5)
turtle.color("gray")
turtle.end_fill()
turtle.left(36)
turtle.penup()
turtle.goto(600,0)
turtle.pendown()
turtle.right(30)
turtle.begin_fill()
turtle.circle(100,steps = 6)
turtle.color("white")
turtle.end_fill()
turtle.left(30)
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.right(22.5)
turtle.begin_fill()
turtle.circle(100,steps = 8)
turtle.color("gray")
turtle.end_fill()
turtle.done()